/**
 * LEO AI KNOWLEDGE GRAPH
 * A centralized repository for Leo AI's local intelligence.
 * Contains 100+ specialized data points.
 */

export const systemPrompt = "You are Leo AI, a highly intelligent and helpful AI assistant. You provide concise, accurate, and professional information across all fields of human knowledge.";

export const KNOWLEDGE_BASE = {
    // Science & Nature
    "light": "Light travels at exactly 299,792,458 meters per second in a vacuum.",
    "water": "Water is H2O, consisting of two hydrogen atoms covalently bonded to one oxygen atom.",
    "gravity": "Gravity is the curvature of spacetime caused by mass and energy, as described by General Relativity.",
    "photosynthesis": "The process by which plants use sunlight, water, and CO2 to create oxygen and energy in the form of sugar.",
    "dna": "Deoxyribonucleic acid is the hereditary material in humans and almost all other organisms.",
    "evolution": "The process by which different kinds of living organisms developed and diversified from earlier forms.",
    "quantum": "Quantum mechanics describes the physical properties of nature at the scale of atoms and subatomic particles.",
    "black hole": "A region of spacetime where gravity is so strong that nothing, not even light, can escape.",
    "oxygen": "The chemical element with symbol O and atomic number 8, essential for most life on Earth.",
    "hydrogen": "The most abundant chemical substance in the universe, constituting roughly 75% of all baryonic mass.",
    "atoms": "The smallest unit of ordinary matter that forms a chemical element.",
    "mitochondria": "Often called the powerhouse of the cell, they generate most of the cell's supply of ATP.",
    "periodic table": "A tabular display of the chemical elements, arranged by atomic number and electron configuration.",
    "entropy": "A thermodynamic property that is a measure of a system's thermal energy per unit temperature that is unavailable for doing useful work.",
    "absolute zero": "The lowest limit of the thermodynamic temperature scale, equivalent to –273.15 degrees Celsius.",
    "supernova": "A powerful and luminous stellar explosion that occurs during the last evolutionary stages of a massive star.",
    "nebula": "An enormous cloud of dust and gas in outer space; some come from the gas and dust thrown out by the explosion of a dying star.",
    "dark matter": "A form of matter thought to account for approximately 85% of the matter in the universe.",
    "tectonics": "The scientific theory that describes the large-scale motion of seven large plates and the movements of a larger number of smaller plates of Earth's lithosphere.",
    "atmosphere": "The envelope of gases surrounding the earth or another planet.",

    // History
    "roman empire": "Ancient Rome's post-Republican period, characterized by autocratic government and vast holdings.",
    "hamlet": "Shakespeare's tragedy about Prince Hamlet of Denmark and his revenge against his uncle.",
    "pyramids": "Ancient masonry structures in Egypt built as tombs for pharaohs.",
    "renaissance": "A fervent period of European cultural, artistic, political, and economic 'rebirth' following the Middle Ages.",
    "industrial revolution": "The transition to new manufacturing processes in Europe and the US, in the period from about 1760 to 1840.",
    "magna carta": "A royal charter of rights agreed to by King John of England in 1215.",
    "french revolution": "A period of far-reaching social and political upheaval in France and its colonies beginning in 1789.",
    "world war i": "A global war originating in Europe that lasted from 28 July 1914 to 11 November 1918.",
    "world war ii": "A global war that lasted from 1939 to 1945, involving the vast majority of the world's countries.",
    "cold war": "A period of geopolitical tension between the United States and the Soviet Union and their respective allies.",
    "civil rights movement": "A decades-long struggle by African Americans and their like-minded allies to end institutionalized racial discrimination.",
    "apollo 11": "The spaceflight that first landed humans on the Moon in 1969.",
    "black death": "A bubonic plague pandemic occurring in Afro-Eurasia from 1346 to 1353; the most fatal pandemic recorded in human history.",
    "ancient greece": "A civilization belonging to a period of Greek history from the Greek Dark Ages to the end of antiquity.",
    "mayan civilization": "A Mesoamerican civilization developed by the Maya peoples, noted for its logosyllabic script and calendars.",
    "great wall of china": "A series of fortifications that were built across the historical northern borders of ancient Chinese states.",
    "viking age": "The period during the Middle Ages when Norsemen known as Vikings undertook large-scale raiding, colonizing, and trading throughout Europe.",
    "samurai": "The hereditary military nobility and officer caste of medieval and early-modern Japan.",
    "ottoman empire": "An empire that controlled much of Southeast Europe, Western Asia, and Northern Africa between the 14th and early 20th centuries.",
    "aztec empire": "An alliance of three Nahua city-states that ruled the area in and around the Valley of Mexico from 1428 until the Spanish conquest.",

    // Technology & AI
    "ai": "Artificial Intelligence is the simulation of human intelligence processes by machines.",
    "javascript": "A high-level, often just-in-time compiled language that is one of the core technologies of the Web.",
    "transformer": "An AI architecture that uses self-attention mechanisms, revolutionizing NLP.",
    "coding": "The process of using a programming language to get a computer to behave how you want it to.",
    "internet": "A global system of interconnected computer networks.",
    "blockchain": "A shared, immutable ledger that facilitates the process of recording transactions and tracking assets in a business network.",
    "cloud computing": "The on-demand availability of computer system resources, especially data storage and computing power.",
    "cybersecurity": "The practice of protecting systems, networks, and programs from digital attacks.",
    "data science": "An interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge from data.",
    "machine learning": "A field of inquiry devoted to understanding and building methods that 'learn' from data.",
    "neural networks": "A series of algorithms that endeavors to recognize underlying relationships in a set of data through a process that mimics the way the human brain operates.",
    "quantum computing": "A type of computation whose stack utilizes the collective properties of quantum states, such as superposition and entanglement.",
    "big data": "Extremely large data sets that may be analyzed computationally to reveal patterns, trends, and associations.",
    "algorithm": "A finite sequence of rigorous instructions, typically used to solve a class of specific problems or to perform a computation.",
    "cryptography": "The practice and study of techniques for secure communication in the presence of third parties.",
    "open source": "Software for which the original source code is made freely available and may be redistributed and modified.",
    "api": "Application Programming Interface; a way for two or more computer programs to communicate with each other.",
    "virtual reality": "A simulated experience that can be similar to or completely different from the real world.",
    "augmented reality": "An interactive experience of a real-world environment where the objects that reside in the real world are enhanced by computer-generated perceptual information.",
    "internet of things": "Describes physical objects with sensors, processing ability, software and other technologies that connect and exchange data with other devices over the Internet.",

    // Geography & World
    "earth": "The third planet from the Sun and the only known to harbor life.",
    "mars": "The fourth planet from the Sun, often called the Red Planet.",
    "sun": "The star at the center of our Solar System.",
    "mount everest": "Earth's highest mountain above sea level, located in the Himalayas.",
    "amazon river": "The largest river by discharge volume of water in the world, located in South America.",
    "sahara desert": "The largest hot desert in the world, covering much of North Africa.",
    "antarctica": "Earth's southernmost continent, containing the geographic South Pole.",
    "pacific ocean": "The largest and deepest of Earth's oceanic divisions.",
    "greenland": "The world's largest island, located between the Arctic and Atlantic oceans.",
    "nile river": "A major north-flowing river in northeastern Africa, historically considered the longest river in the world.",
    "tokyo": "The capital and most populous city of Japan.",
    "paris": "The capital and most populous city of France, known as the City of Light.",
    "new york city": "The most populous city in the United States, a global hub for finance and culture.",
    "london": "The capital and largest city of England and the United Kingdom.",
    "grand canyon": "A steep-sided canyon carved by the Colorado River in Arizona, United States.",
    "great barrier reef": "The world's largest coral reef system, located in the Coral Sea off the coast of Australia.",
    "machu picchu": "A 15th-century Inca citadel located in the Eastern Cordillera of southern Peru.",
    "galapagos islands": "An archipelago of volcanic islands distributed on either side of the equator in the Pacific Ocean, famous for Darwin's studies.",
    "dead sea": "A salt lake bordered by Jordan to the east and Israel and the West Bank to the west.",
    "mount kilimanjaro": "A dormant volcano in Tanzania, the highest mountain in Africa.",

    // Arts & Culture
    "mona lisa": "A half-length portrait painting by Italian artist Leonardo da Vinci, considered an archetypal masterpiece of the Italian Renaissance.",
    "the starry night": "An oil-on-canvas painting by the Dutch Post-Impressionist painter Vincent van Gogh.",
    "beethoven": "Ludwig van Beethoven was a German composer and pianist; a crucial figure in the transition between the Classical and Romantic eras.",
    "mozart": "Wolfgang Amadeus Mozart was a prolific and influential composer of the Classical period.",
    "jazz": "A music genre that originated in the African-American communities of New Orleans in the late 19th and early 20th centuries.",
    "architecture": "The art and technique of designing and building, as distinguished from the skills associated with construction.",
    "sculpture": "The branch of the visual arts that operates in three dimensions.",
    "cinema": "The art of making motion pictures.",
    "photography": "The art, application, and practice of creating durable images by recording light.",
    "literature": "Any body of written works, but it is also used more narrowly for writings specifically considered to be an art form.",
    "opera": "A form of theatre in which music is a fundamental component and dramatic roles are taken by singers.",
    "ballet": "A type of performance dance that originated during the Italian Renaissance in the 15th century.",
    "surrealism": "A cultural movement that began in the early 1920s, best known for its visual artworks and writings.",
    "impressionism": "A 19th-century art movement characterized by small, thin, yet visible brush strokes and open composition.",
    "picasso": "Pablo Picasso was a Spanish painter, sculptor, and one of the most influential artists of the 20th century.",
    "the odyssey": "One of two major ancient Greek epic poems attributed to Homer.",
    "divine comedy": "A long Italian narrative poem by Dante Alighieri, begun c. 1308 and completed in 1320.",
    "haiku": "A type of short-form poetry originally from Japan, consisting of three phrases with a 5, 7, 5 syllable structure.",
    "manga": "Comics or graphic novels originating from Japan.",
    "mythology": "A body of myths and teachings that belong to a particular religion or culture.",

    // Philosophy & Logic
    "philosophy": "The study of general and fundamental questions about existence, knowledge, values, and reason.",
    "socrates": "A Greek philosopher from Athens who is credited as one of the founders of Western philosophy.",
    "plato": "An Athenian philosopher during the Classical period in Ancient Greece, founder of the Academy.",
    "aristotle": "A Greek philosopher and polymath during the Classical period in Ancient Greece, taught by Plato.",
    "stoicism": "A school of Hellenistic philosophy that flourished in Ancient Greece and Ancient Rome.",
    "nihilism": "The philosophical belief that suggests the lack of belief in one or more reputedly meaningful aspects of life.",
    "existentialism": "A form of philosophical inquiry that explores the nature of existence by emphasizing the experience of the human subject.",
    "logic": "The study of correct reasoning.",
    "ethics": "The branch of philosophy that involves systematizing, defending, and recommending concepts of right and wrong conduct.",
    "metaphysics": "The branch of philosophy that examines the fundamental nature of reality, including the relationship between mind and matter.",
    "epistemology": "The branch of philosophy concerned with knowledge.",
    "socialism": "A political, social, and economic philosophy encompassing a range of economic and social systems characterized by social ownership.",
    "capitalism": "An economic system based on the private ownership of the means of production and their operation for profit.",
    "democracy": "A form of government in which the people have the authority to deliberate and decide legislation.",
    "utilitarianism": "A family of normative ethical theories that prescribe actions that maximize happiness and well-being for all affected individuals."
};
